# Name   : requiredpackagesinstall
# Author : Joe W. Byers
# Date   : 02/26/2014
# Version: 1.0001
# Aim    : 
# Mail   : <<<ecjbosu@aol.com>>>
#==============================================================================
#Install the Base plus a few Quantitative libraries 
requirepackagesinstall<-function(others=F, cranmirror=113, includeR_Forge=T) {
# others=T will install the 2000+ other packages that may benefit.

#      others=T
#      cranmirror=113
#      includeR_Forge=T

#set the cranmirroor
chooseCRANmirror(ind=cranmirror)

repos = getOption("repos");

if (includeR_Forge) options("repos"= c(repos, "http://R-Forge.R-project.org"));

source("http://www.rmetrics.org/Rmetrics.R")


   #options(install.packages.check.source = FALSE)
   
   basePacks <- c("base","boot","class","cluster","codetools","compiler",
      "datasets","foreign","graphics","grDevices","grid","KernSmooth","lattice",
      "MASS","Matrix","methods","mgcv","nlme","nnet","parallel","rpart",
      "spatial","splines","stats","stats4","survival","tcltk","tools",
      "translations","utils");

   currentPacks <-c("RJDBC","hwriter","xlsxjars","xlsx","RCurl","XML","xtable",
      "tis","reshape","xts","lubridate","rJava","base64enc","digest", "rvest",
      "splus2R","R.devices","R.matlab","DBI","memoise","packrat", "R6", "readODS",
      "plyr","R.methodsS3","R.oo","R.utils","stringr","stringi","bibtex",
      "quantmod","PerformanceAnalytics", "lpSolve","lpSolveAPI", "blotter",
      "rsconnect");
      
      
   rMetrics<-pkgsRmetrics(); # or next
   rMetrics <- c("timeDate","timeSeries","fImport","fBasics","fArma",
      "fGarch","fNonlinear","fUnitRoots","fTrading","fMultivar",
      "fRegression","fExtremes","fCopulae","fBonds","fOptions",
      "fExoticOptions","fAsianOptions","fAssets","fPortfolio",
      "BLCOP","FKF","ghyp","HyperbolicDist","randtoolbox","rngWELL",
      "schwartz97","SkewHyperbolic","VarianceGamma","stabledist")

   rMetricsRequires<-c("bitops","mnormt","zoo","DEoptimR","slam","gtools",
      "gdata","caTools","gss","urca","sn","polspline","lmtest","robustbase",
      "quadprog","Rglpk","RUnit","numDeriv","gplots","mvtnorm",
      "DistributionUtils","GeneralizedHyperbolic");
   
   mine <- c(getOption('defaultPackages'),currentPacks, rMetrics);
   
mostCommonDepends<-c("rgl","igraph","ape","Formula","BB","geepack","sp","Hmisc",
"scales","plotrix","RColorBrewer","abind","coda","R.cache","R.filesets",
"matrixStats","R.huge","R.rsp","scatterplot3d","vcd","seriation","polynom",
"deSolve","gstat","RSQLite","sendmailR","brew","fail","pbapply","wpp2012",
"hett","car","MCMCpack","maptools","colorspace","flexmix","modeltools",
"sandwich","Rcpp","RcppArmadillo","strucchange","raster","e1071","fields",
"permute","ROCR","gbm","colorRamps","pamr","randomForest","Boruta","caret",
"tgp","mlegp","penalizedSVM","SoDA","cubature","truncdist","spam","reshape2",
"foreach","polycor","sfsmisc","glmmML","miscTools","VGAM","multcomp","actuar",
"statmod","tweedie","ggplot2","ade4","R2HTML","useful","proto","oce",
"isotone","energy","rootSolve","AlgDesign","clusterSim","rgeos","RandomFields",
"gsl","ADGofTest","pspline","copula","vines","truncnorm","CRF","expm","corpcor",
"phangorn","rgenoud","biglm","minqa","tpr","lgtdl","pls","latticeExtra",
"RJSONIO","base64","markdown","mvbutils","httr","whisker","evaluate","disclap",
"distr","distrEx","distrSim","distrTEst","distrTeach","RandVar","distrMod",
"SweaveListingUtils","startupmsg","KFAS","lme4","combinat","lhs",
"iterators","pkgmaker","gmp","trust","hexbin","TSP","extrafontdb","Rttf2pt1",
"BBmisc","fastmatch","ltsa","filehash","glmnet","lars","leaps","muhaz",
"extrafont","sapa","tseries","fracdiff","wmtsa","BsMD","moments","lambda.r",
"futile.options","DAAG","oro.nifti","movMF","gridExtra","geometry","subplex",
"msm","mstate","data.table","splancs","MBA","RSEIS","RFOC","GEOmap","gtable",
"RgoogleMaps","png","rjson","mapproj","Runuran","PolynomF","CommonJavaJars",
"magic","qvcalc","relimp","testthat","RSAGA","rgdal","aqp","plotKML",
"quantregForest","spacetime","ggmap","popgraph","locfit","ash","ks","EMD","Iso",
"fda","SparseM","TeachingDemos","hydroTSM","automap","elliptic","contfrac",
"appell","kappalab","baseline","signal","evd","spcosa","spatstat","network",
"sets","prodlim","ff","sciplot","genalg","kernlab","mitools","formatR","highr",
"lmodel2","sna","gWidgets","pbivnorm","MBESS","FNN","yuima",
"harvestr","dostats","pbkrtest","gvlma","shapes","pcaMethods","SparseGrid",
"shape","downloader","readBrukerFlexData","readMzXmlData","R2admb","optimx",
"dfoptim","cba","exactRankTests","nnls","stashR","denstrip","cairoDevice",
"futile.logger","doBy","fastGHQuad","RGCCA","pheatmap","ipred","reportr","aod",
"HI","wordcloud","Ohmage","rms","skmeans","clue","gsubfn","rSymPy","rJython",
"partitions","Rsolnp","HardyWeinberg","emulator","compositions",
"robCompositions","labdsv","vegan","bayesm","statnet.common","objectSignals",
"NLP","openNLPdata","getopt","ucminf","BHH2","phytools","coin","mratios",
"binMto","RWeka","rcdd","phylosim","snow","rlecuyer","penalized","gnm","matlab",
"animation","gridBase","misc3d","pixmap","classInt","plsdof","plsRglm",
"spls","mixOmics","bipartite","games","calibrate","RcppEigen","lava",
"multilevel","chron","openNLP","reports","tm","venneuler","ellipse","lavaan",
"sem","jpeg","BDgraph","hdrcde","RSNNS","rtematres","biclust","isa2","ggthemes",
"roxygen2","OAIHarvester","wavethresh","gamm4","RLRsim","tsoutliers",
"FRACTION","mcmc","PhaseType","ascii","knitr","knitcitations","RPostgreSQL",
"cmprsk","snowfall","matrixcalc","kknn","jsonlite","pcaPP",
"registry","ROI","googleVis","quantreg","gam","minpack.lm","norm",
"Rwave","tree","maxent","tau","rphast","nloptr","spd","maps","RWekajars",
"dichromat","munsell","labeling","sm","VineCopula","survey","qgraph",
"lisrelToR","rockchalk","rggobi","gclus","Cairo","doParallel","circular",
"httpuv","qcc","elasticnet","intervals","spdep","mmap","spBayes",
"deldir","tensor","polyclip","LearnBayes","akima","forecast",
"Rook","shiny","tframe","tfplot","tseriesChaos","vars",
"setRNG","tframePlus","fame","TSsql","TSdbi","pastecs","tester","yaml",
"yacca");

#from packageCleanup

requireForCurrentPackageSet<-c(); 



otherpacks<-c("abc","abn","acs","ActuDistns","ada","adabag","adagio","AdaptFit",
"AdMit","ads","AER",
"aftgee","AGD","Agreement","AGSDest","ahaz","AID","AIM","akmeans","alabama",
"allan","allanvar","AllPossibleSpellings","alphashape3d","alr3","alr4","ALS",
"amap","amen","AmericanCallOpt","AMORE","anacor","anoint",
"aplpack","apt","arf3DS4","arfima","arrayhelpers","ars","ARTIVA",
"arules","arulesNBMiner","arulesViz","aspace","aspect",
"assertive","AssetPricing","astroFns","astsa","asympTest","asypow","AtelieR",
"AtmRay","AUCRF","audit","autopls","AutoSEARCH","aws","awsMethods",
"aylmer","B2Z","BACCO","backtest","BACprior","BAEssd","Barnard",
"BAS","BaSTA","batade","batch","BatchJobs","batchmeans","BayesBridge",
"BayesFactor","bayesGARCH","bayesGDS","BayesLCA","BayesLogit","bayesMCClust",
"BayesNI","bayesPop","bayespref","bayesQR","BayesSingleSub",
"bayesSurv","bayesTFR","Bayesthresh","BayesTree","BayesValidate","BayesVarSel",
"BayesX","BayesXsrc","BayHap","BayHaz","BaylorEdPsych","BAYSTAR","bbemkr",
"bbmle","BBMM","BCBCSF","BCE","BCEA","Bchron","Bclim","bcv","bda",
"bdsmatrix","beanplot","benchmark","Benchmarking","Bergm","Bessel","bestglm",
"betareg","betategarch","bfa","bfast","bfp","BGLR","bgmm","BGSIMD","BH","Bhat",
"biasbetareg","BiasedUrn","bibtex","BiDimRegression","bifactorial","bigdata",
"biglars","bigml","bigRR","bild","bindata","binGroup","binom","binomialcftp",
"binomlogit","binomTools","binseqtest","bit64",
"bivarRIpower","biwavelet","biwt","BlakerCI","BLCOP","blighty","blm",
"blockmodeling","blockrand","blockTools","BLR","BMA","bmem",
"Bmix","BMN","bmp","BMS","bnlearn","BNPdensity","BoolNet",
"boostSeq","bootES","bootRes","bootruin","bootspecdens","bootStepAIC",
"bootstrap","BoSSA","bpca","bpcp","bpkde","bqtl","brainwaver","bReeze","brglm",
"brnn","Brobdingnag","broman","BSDA","BurStFin","BurStMisc",
"bursts","bvenn","bvls","bvpSolve","BVS","CADFtest","calibrator",
"candisc","capushe","capwire","CARBayes","caroline",
"cat","catdata","catspec","CausalGAM","CCA","ccgarch","CCM","CCP","CDFt",
"CDNmoney","CDVine","cec2005benchmark","celestial","censReg",
"CensRegMod","CePa","cfa","cg","cggd","cgh","ChainLadder","CHCN",
"cheb","cherry","ChoiceModelR","choplump","CHsharp","CircNNTSR",
"CircStats","CITAN","CityPlot","Ckmeans.1d.dp","classGraph","classifly","clhs",
"climdex.pcic","clime","cloudUtil","clpAPI","CLSOCP","cmrutils",
"coarseDataTools","cobs","CoClust","coefplot","colortools",
"CombMSC","commandr","CommonTrend","compare","compareGroups","CompareTests",
"comparison","compeir","compHclust","CompLognormal",
"compoisson","COMPoissonReg","compound.Cox","Compounding","CompQuadForm",
"CompRandFld","compute.es","ConConPiWiFun","concor","concreg","condGEE",
"condmixt","conf.design","conics","conjoint","ConjointChecks",
"constrainedKriging","conting","contrast","ConvCalendar",
"ConvergenceConcepts","copBasic","copulaedas",
"CopulaRegression","CopyDetect","corcounts","CORElearn","corHMM","corpora",
"CorrBin","corrgram","corrplot","corrsieve","cosmoFns","cosso","costat",
"cotrend","COUNT","countrycode","CoxBoost","coxphf","coxphw","coxrobust","CPE",
"cplm","cpm","CPMCGLM","Cprob","CR","cramer","crank","crantastic",
"crblocks","CreditMetrics","crimCV","CRM","crn","crossmatch","crp.CSFP","crrSC",
"crrstep","crs","CRTSize","cshapes","cslogistic","cts",
"CTT","ctv","Cubist","cudaBayesregData","cudia","CUMP","cumplyr","cumSeg",
"currentSurvival","curvetest","cusp","cvAUC","cvplogistic","cvq2","CVST",
"CVThresh","cvTools","cwhmisc","cxxfunplus","dae","daewr","DatABEL",
"dataframes2xls","datamap","datamart","datautils",
"dataview","date","dblcens","dbmss","dcemriS4","dcv","ddst","deal","debug",
"depmix","depmixS4","depth","depthTools","descr","deseasonalize",
"detect","deTestSet","detrendeR","devEMF","devtools","dglars","dglm","dgmb",
"dgof","dhglm","diagram","DiagTest3Grp","directlabels",
"DirichletReg","dirmult","disclapmix","DiscreteInverseWeibull",
"DiscreteLaplace","discreteMTP","discretization","DiscriMiner","disp2D",
"displayHTS","dispmod","Distance","distfree.cr","distrDoc","distrEllipse",
"distrom","dlmodeler","dlnm","dma","dmt","DMwR","DnE","doRedis","doRNG",
"doSNOW","DPpackage","dr","drawExpression","drm","ds","dse",
"dsm","DSpat","DTDA","DTK","dtw","dummies","dyn","dynamicTreeCut","dynaTree",
"DynClust","dynCorr","dynlm","dynpred","earlywarnings","earth","EasyABC",
"easyanova","eba","ebal","EbayesThresh",
"ebdbNet","EBMAforecast","EBS","Ecdat","ecespa","ecodist","edcc","EDISON",
"editrules","EDR","edrGraphicalTools","effects","EffectStars","eha",
"eigeninv","eigenmodel","eive","EL","elec","elmNN","elrm","emdist","emg",
"emplik","emplik2","EMT","enaR","ensembleBMA",
"entropy","epr","EQL","equate","equivalence","erer","ergm","ergm.count",
"ergm.userterms","ESG","estout","etable","ETLUtils","etm","EvalEst",
"evdbayes","eVenn","events","eventstudies","evir","evtree","Exact",
"exact2x2","exactci","ExactCIdiff","exactLoglinTest","exams","ExpDes",
"expectreg","experiment","expert","ExPosition","expsmooth","exptest",
"extraBinomial","extraTrees","extRemes",
"extremevalues","ez","ezglm","ezsim","FactMixtAnalysis","FactoClass",
"FactoMineR","factorQR","Fahrmeir","FAiR","fanc","fANCOVA","fanovaGraph",
"fanplot","faoutlier","far","fArma","fAsianOptions","fAssets","fast",
"fastcluster","fastcox","fastICA","FastImputation","fastR","FastRWeb","fastSOM",
"fBasics","fBonds","fCertificates","fCopulae","fds","fdth","feature","features",
"fechner","fExoticOptions","fExtremes","ffbase","ffmanova","fftw",
"fgac","fGarch","FGN","fgof","fgui","FieldSim","filehashSQLite","fImport",
"FinancialInstrument","FinAsym","FindAllRoots","FindIt","fingerprint","FinTS",
"FisherEM","fit.models","fit4NM","FitAR","FitARMA","fitdistrplus",
"fitDRC","FITSio","FKF","flexclust","FlexParamCurve","flexsurv","flip",
"fma","FME","fmri","fmsb","FMStable","fmt","fMultivar",
"fNonlinear","foba","fontcm","fOptions","ForeCA","ForImp","FormalSeries",
"formula.tools","fortunes","forward","fossil","fpc","fpca","fPortfolio","fpow",
"fpp","fptdApprox","fracprolif","fractal","fractaldim","fractalrock","FRAPO",
"FRB","frbs","FRCC","freeknotsplines","fRegression","freqMAP","FrF2",
"FrF2.catlg128","frmqa","frontier","frontiles","frt","FTICRMS","ftnonpar",
"fTrading","fts","fun","FunCluster","FuncMap","functional",
"fUnitRoots","futile.any","futile.matrix","futile.paradigm","fuzzyFDR",
"FuzzyNumbers","fuzzyRankTests","fwdmsa","FWDselect","fwi.fbp","fxregime",
"G1DBN","galts","gamair","GAMBoost","gamboostLSS","gamclass","gamlr","gamlss",
"gamlss.add","gamlss.cens","gamlss.data","gamlss.demo","gamlss.dist",
"gamlss.mx","gamlss.nl","gamlss.tr","gamlss.util","gammSlice","gaussDiff",
"gaussquad","gb","gcmr","gcookbook","gdimap","gdistance","gee",
"geeM","geiger","gems","GENEAread","GeneF","GenKern","genlasso","GenOrd",
"genridge","GenSA","genSurv","geo","geoCount","GeoLight",
"geomapdata","geonames","geophys","geoR","geoRglm","geosphere","geospt",
"geotools","geotopbricks","GeoXp","geozoo","GEVcdn","GGally","ggdendro",
"GGEBiplotGUI","gglasso","GGMselect","ggparallel","ggsubplot","GhcnDaily",
"ghyp","gibbs.met","GillespieSSA","giRaph","GISTools","Giza","glasso","gld",
"GLDEX","gldist","glm2","glmc","glmdm","glmmGS",
"glmmLasso","glmnetcr","glmpath","glmpathcr","glmulti","glmx",
"globalboosttest","glogis","glpkAPI","gMCP","GMD","gmm","GMMBoost",
"gmodels","gmt","gMWT","gnmf","gnumeric","goalprog","gof","gogarch",
"googlePublicData","goric","gpairs","GPArotation","gPdtest",
"GPfit","gProfileR","GPseq","gptk","GPvam","grade",
"granova","gRapHD","GrapheR","graphicsQC",
"GrassmannOptim","Grid2Polygons","gridDebug","gridGraphviz",
"gridSVG","GriegSmith","grImport","grofit","grouped","GroupSeq","growcurves",
"growthrate","grplasso","grpreg","grt","GSA","gsarima","gsbDesign","gsDesign",
"gsg","GSIF","GSM","gsmoothr","gtcorr","gte","gtx","Guerry","gumbel",
"GUniFrac","gvcm.cat","GWAF","GWASExactHW","gwerAM","GWG",
"GWRM","HAC","HadoopStreaming","HapEstXXR","hash","hbmem",
"hbsae","hda","HDclassif","hdeco","hdlm","heatmap.plus","heatmapFit","heavy",
"helloJavaWorld","heplots","hexView","hgam","hglm","HGNChelper","hht",
"HiddenMarkov","HiDimDA","hier.part","hierarchicalDS","HIest","highfrequency",
"highlight","highriskzone","hiPOD","hisemi","HistData",
"histogram","HLMdiag","hmeasure","HMM","hmm.discnp","hmmm","HMP",
"HMPTrees","HMR","holdem","Holidays","homals","homeR","homtest",
"Hotelling","hotspots","howmany","HPbayes","HSAUR","HSAUR2","hSDM","HSROC",
"HTMLUtils","hts","httpRequest","huge","HW.pval","hwde","HWEBayes",
"HWEintrinsic","hwriterPlus","hybridHclust","HybridMC","hydroGOF","HydroMe",
"hydroPSO","HyperbolicDist","hyperdirichlet","hypergeo",
"hyperSpec","HyPhy","hypothesestest","hzar",
"ibd","ibdreg","ibr","IBrokers","ic.infer","IC2","ic50","icaOcularCorrection",
"ICC","ICE","ICEinfer","iCluster","ICS","ICSNP","idbg",
"identity","IDPmisc","idr","ifs","ifultools","iGasso","IgorR","igraphdata",
"igraphtosonia","Imap","imguR","IMIS","imprProbEst","imputeMDR","imputeYn",
"IndependenceTests","indicspecies","ineq","InfDim","inference","influence.ME",
"infoDecompuTE","informR","infotheo","infutil","inline","inlinedocs",
"insideRODE","insol","intamap","intamapInteractive",
"Interact","InteractiveIGraph","intergraph","Interpol",
"Interpol.T","intpoint","intReg","intRegGOF","introgress","intsvy","iplots",
"IPMpack","ipw","IQCC","irace","iRegression","irlba","irr","irtoys","irtrees",
"ISBF","ISDA.R","isdals","ismev","isocir","ISOcodes","isopam","isopat",
"IsotopeR","ISOweek","ISwR","iterLap","itertools","its","itsmr","ivbma",
"JavaGD","JGL","JGR","JM","JMbayes","Jmisc",
"JohnsonDistribution","joineR","jointDiag","JOP","JoSAE",
"Julia","kelvin","Kendall","kequate","kerdiest","kernelFactory","KernSmoothIRT",
"kin.cohort","kinfit","klaR","klausuR","klin","km.ci","kmi","kml","kml3d",
"KMsurv","knnGarden","kohonen","kolmim","koRpus","Kpart","kriging","KrigInv",
"KRLS","kSamples","kst","kulife","kza","kzft","kzs","labeledLoop",
"labeltodendro","labstatR","laercio","LaF","Lambda4","LambertW","landsat",
"languageR","laser","lasso2","lassoshooting","latdiag",
"latentnet","Laterality","latticeDensity","LatticeKrig",
"lava.tobit","lavaan.survey","lawstat","lazyWeave","lcda",
"LCFdata","lcmm","lda","ldbounds","LDcorSV","ldlasso",
"ldr","LDtests","LeafAngle","LeLogicielR","lessR","lestat","lfe","lfstat","lga",
"lgcp","libamtrack","LiblineaR","LICORS","lifecontingencies","LifeTables",
"LIHNPSD","likelihood","LIM","limitplot","limSolve","LinearizedSVR","lineup",
"linkcomm","linLIR","linprog","lint","liso","lisp","LIStest","lle",
"lmec","LMERConvenienceFunctions","lmerTest","lmeSplines","LMest",
"lmf","lmm","lmmlasso","lmom","lmomco","Lmoments","lmomRFA",
"lmSupport","loa","localdepth","localgauss","locfdr","Lock5Data",
"locpol","log4r","LogConcDEAD","logconcens","logcondens","logcondiscr",
"logging","LogicReg","logistf","LogitNet","logitnorm","loglognorm","logmult",
"logspline","longclust","longitudinal","longitudinalData",
"longmemo","longpower","loop","LoopAnalyst","lordif","lorec","LowRankQP","lpc",
"LPCM","lpint","lpridge","lqa","lqmm","LS2W","lsa","LSC","LSD",
"lshorth","lsmeans","lspls","lss","luca","Luminescence","MAc",
"MAclinical","MAd","mada","magicaxis","mail","MAINT.Data","makeProject",
"MALDIquant","MAMS","manipulate","mapdata",
"MapGAM","MAPLES","mapplots","maptree","mAr","mar1s",
"maRketSim","marqLevAlg","MARSS","MAT","Matching",
"MatchIt","mathgraph","matie","MatrixEQTL","MatrixModels","MATTOOLS",
"MaXact","maxLik","maxlike","maxstat","MBCluster.Seq","MBmca","mbmdr","mboost",
"mc2d","MCAPS","mcbiopi","mcclust","mcga","mcgibbsit","MChtest",
"mcll","mclogit","mclust","MCMCglmm","mcmcse","mco","Mcomp",
"MCPAN","MCPerm","MCPMod","mcprofile","mcr","mcsm",
"McSpatial","mda","mded","MDM","MDPtoolbox","MDR","meboot",
"MedOr","medSTC","meifly","mem","memisc","MEMSS","MergeGUI","merror",
"Metrics","metRology","mets","MExPosition",
"mFilter","mfp","mgpd","mgraph","MHadaptive","mhsmm","mht","mhurdle",
"mice","micEcon","micEconAids","micEconCES","micEconSNQP",
"microbenchmark","micromap","MImix","MindOnStats","minerva","Miney",
"miniGUI","minimax","minxent","MIPHENO","miscF","miscFuncs","missForest",
"MissingDataGUI","missMDA","MitISEM","mix","mixAK","mixcat","mixdist",
"mixer","mixexp","MixMAP","mixPHM","mixRasch","mixreg","MixSim",
"mixsmsn","mixtools","mkin","MKmisc","mkssd","mlbench","MLCM","MLDS",
"mlearning","MLEcens","mleur","mlica2","mlmmm","mlmRev","mlogit",
"mlogitBMA","mlPhaser","MM","mmand","mmcm","mmds","mmeln",
"mmm","mmm2","MMS","MNM","MNP","Mobilize","MOCCA",
"Modalclust","modeest","modehunt","modelfree","ModelGood","ModelMap",
"modTempEff","mombf","mondate","monomvn","MonoPoly","monreg","mosaic",
"mpa","MPDiR","MplusAutomation","mpm","mpmcorrelogram","mpmi","mpoly","mpt",
"MPTinR","MPV","mra","MRCE","mrds","mritc","mRm","mRMRe",
"MSBVAR","MSeasyTkGUI","msgl","msr","msSurv","MSwM","mtsdi",
"MTurkR","MUCflights","MuFiCokriging","multcompView","MultEq",
"multgee","multibiplotGUI","multicool",
"MultiLCIRT","MultinomialCI","multinomRob","MultiOrd","MultiPhen","multiPIM",
"multipol","multisensi","multitable","multitaper","multivator","multxpert",
"MuMIn","munfold","muRL","muStat","MVA","mvabund","MVB","mvc",
"mvinfluence","mvna","mvngGrAd","mvnmle","mvnormtest","mvoutlier",
"mvProbit","MVR","mvsf","mvShapiroTest",
"mvtsplot","mxkssd","myepisodes","NADA","nadiv","namespace","nanop",
"nCDunnett","ncf","ncg","ncvreg","ndl","NeatMap","neldermead",
"NetCluster","networkDynamic","networksis","nFactors","ngspatial","NHPoisson",
"NightDay","NISTnls","nleqslv","nlmeODE","nlmeU","nlmrt","NLRoot",
"nls2","nlsmsn","nlstools","nlts","NMFN","NMOF","nodeHarvest",
"noia","nonlinearTseries","nonparaeff","NonpModelCheck","nopp","nor1mix",
"NormalGamma","normalp","NORMT3","normwhn.test","nortest","nose","notifyR",
"Nozzle.R1","np","nparcomp","nparLD","NPCD","npde","NPHMC","nplplot","npmlreg",
"NPMPM","npmv","nppbib","NPsimex","NScluster","nullabor","numbers",
"Oarray","objectProperties","obliclus","oblique.tree","obliqueRF","OceanView",
"ODB","odfWeave","odfWeave.survey","oem","okmesonet",
"OligoSpecificitySystem","OLScurve","onion","OOmisc","opefimor","openair",
"openintro","OpenRepGrid","OpenStreetMap","operator.tools","operators","ops",
"optextras","optimbase","optimsimplex","OptInterim","optmatch","optparse",
"optpart","orclus","ORCME","orcutt","orddom","ORDER2PARENT",
"OrdFacReg","ordinal","OrdMonReg","ordPens","ORIClust","orientlib","orloca",
"orloca.es","ORMDR","orthogonalsplinebasis","orthopolynom","osDesign","osmar",
"ouch","outliers","OUwie","oz","pa","pacbpred","pack","packdep",
"packHV","PAGI","pairedCI","pairheatmap","PairViz","pairwiseCI","pamm","pan",
"pander","ParamHelpers","paran","parcor","parfm","parfossil","parma",
"parmigene","partDSA","partialOR","partitionMap","partitionMetric","partsm",
"party","partykit","parviol","PAS","pavo","PBImisc","PBSadmb","PBSddesolve",
"PBSmapping","PBSmodelling","pcaL1","PCICt","PCIT",
"pcse","pdc","pdfCluster","pdist","PDSCE","Peaks","pear","PearsonDS",
"PearsonICA","pec","pencopula","pendensity","penDvine",
"pensim","peperr","peplib","pequod","perARMA","perm",
"perry","perturb","pesticides","pgam","pglm","pgmm",
"pgs","phia","phmm","phtt","PIPS","PKI","plan",
"PlayerRatings","playwith","plgp","plmm",
"pln","plot3D","plotGoogleMaps","plotmo","plotpc","plotSEMM","plRasch",
"plsdepot","plspm","plsRbeta","plsRcox","plugdensity","plumbr","plus","pmg",
"pmlr","pmml","pmmlTransformations","pmr","pnmtrem","poibin",
"PoiClaClu","poilog","poisson.glm.mix","PoissonSeq","poistweedie","poLCA",
"polyapost","polySegratio","polySegratioMM","polywog",
"Pomic","pomp","pooh","popbio","popgen","PopGenKit","PopGenome",
"popReconstruct","portes","portfolio","portfolioSim","potts",
"PottsUtils","PP","ppcor","ppls","pps","PPtree","prabclus","pracma",
"pragma","PredictABEL","PredictiveRegression","predmixcor",
"prefmod","PReMiuM","PresenceAbsence","prettyGraphs","prettyR","prevR","prim",
"primer","princurve","PRISMA","PrivateLR","prLogistic","prob","ProbForecastGOP",
"pROC","ProDenICA","profdpm","ProfessR","ProfileLikelihood",
"profileModel","profr","proftools","ProgGUIinR","proj4","ProjectTemplate",
"PropCIs","proteomicdesign","protoclust","proxy","PSAgraphics","pscl","pseudo",
"PSM","pso","pspearman","PST","psy","ptinpoly","PtProcess","ptw",
"pvar","pvclass","pvclust","PVR","pwr","PwrGSD","pwt","pxR","pyramid",
"qat","QCA","QCA3","QCAGUI","qLearn","qmap","qmrparser","qpcR",
"qPCR.CT","qrfactor","QRM","qrnn","QSARdata","qtl",
"qtlbook","qtlDesign","qtlhot","qtlmt","quadrupen",
"qualV","quantchem","quantregGrowth","quantspec",
"queueing","QUIC","R0","R1magic","R2BayesX","R2Cuba",
"r2dRue","R2G2","r2lh","R2MLwiN","R2STATS","r2stl","R2SWF",
"r4ss","race","RadioSonde","rainbow","ramps","randaes","random",
"random.polychor.pa","randomForestSRC","randomGLM","randomizeBE","randomLCA",
"randomNames","randtoolbox","rangeMapper","RankAggreg",
"rankhazard","RANN","rapport","RArcInfo","rasclass","rasterVis",
"rateratio.test","rationalfun","RAtmosphere","rAverage","rbamtools","rbefdata",
"rbenchmark","rBeta2009","rbounds","rbundler","RCALI",
"Rcapture","RCassandra","rcdk","Rcgmin","rChoiceDialogs","Rclusterpp","rCMA",
"RcppBDT","RcppClassic","RcppClassicExamples","RcppCNPy","RcppDE",
"RcppExamples","RcppGSL","RcppProgress","RcppRoll","RcppSMC","RcppXts","Rcsdp",
"rCUR","Rd2roxygen","rdatamarket","rdd","rdetools","RDIDQ","Rdistance","rDNA",
"Rdpack","rdryad","RDS","Rdsm","ReacTran","readbitmap","readMLData","reams","ReCiPa","ref",
"refund","REGENT","reglogit","regress","regsubseq",
"regtest","rehh","rela","relaimpo","relations","relax","reldist",
"relevent","Reliability","ReliabilityTheory","reliaR","relSim","relsurv",
"remix","rEMM","remMap","Reol","RepeatedHighDim","repolr",
"reporttools","REPPlab","represent","reshapeGUI","ResourceSelection",
"restorepoint","retimes","reweight","RFGLS",
"rfigshare","RFinanceYJ","Rfit","RFLPtools","rfPermute",
"rgam","rGammaGamma","rgcvpack","rgexf","RGIFT","RH2","rHpcc",
"ri","ridge","Ridit","RIFS","rindex","RInside",
"riskRegression","risksetROC","RISmed","RItools","riv","RJaCGH","rje",
"RKEA","rknn","rkt","RM2","RMallow","RMark","RMAWGEN","RMC","rminer","Rmisc","Rmixmod",
"RMongo","rmongodb","rms.gof","RMTstat",
"RNCBIEUtilsLibs","RNCEP","RNetCDF","RNetLogo","rngSetSeed","rngtools",
"rngWELL","rngwell19937","RNiftyReg","ROAuth","RobAStBase",
"robeth","robfilter","RobRex","robust","RobustAFT","robustfa","robustgam",
"robustHD","robustloggamma","RobustRankAggreg","robustreg","robustX","rocc",
"rococo","ROCwoGS","RODBC","RODM","ROI.plugin.glpk",
"ROI.plugin.quadprog","ROI.plugin.symphony","ROptEst",
"ROptEstOld","ROptRegTS","ror","royston","rpartScore","RPCLR",
"rpf","rPlant","rplos","rplotengine","RPMM","rportfolios","rpsychi",
"rpubchem","RQDA","Rquake","RQuantLib","Rramas","rrBLUP",
"rrBlupMethod6","rrcov","rrcovHD","rrcovNA","rredis","RRF",
"rriskDistributions","rrlda","RSA","rsae","RSclient",
"rscproxy","rseedcalc","rsem","rSFA","rsgcc",
"RSiena","RSKC","rsm","RSofia","rspa",
"rspear","Rssa","rstiefel","rstream","Rsundials",
"RSurvey","rtape","RTextTools","rtf","rtfbs","rtiff",
"RTOMO","rtop","rts","rugarch","Runiversal","RunuranGUI","rv",
"RVAideMemoire","rvertnet","rvgtest","RVtests","RWeather",
"Rwinsteps","rworldmap","rworldxtra","rwt","RxCEcolInf",
"RXKCD","RXMCDA","RXshrink","Rz","sac","saemix","SAFD","safeBinaryRegression",
"SAM","SamplerCompare","sampleSelection","samplesize","SampleSizeMeans",
"SampleSizeProportions","sampling","samplingbook","SamplingStrata",
"samplingVarEst","SAPP","sas7bdat","SAScii","SASmixed","saves",
"saws","sBF","sbgcop","SBSA","sca","scagnostics","scam","scaRabee",
"schoolmath","schwartz97","scio","SciViews","SCMA","ScottKnott","scout",
"SCperf","scrapeR","ScreenClean","scrime","scriptests","SCRT","SDaA",
"SDD","sddpack","sde","sdef","sdnet","sdprisk","sdtoolkit",
"SearchTrees","seas","season","SECP","secr","seeg","seg","segmented",
"Segmentor3IsBack","SEL","selectiongain","selectMeta","selectr","SeleMix",
"semdiag","semGOF","SemiPar","SemiParSampleSel",
"semisupKernelPCA","SEMModComp","semPlot","semPLS","semTools",
"sendplot","sensitivity","SensitivityCaseControl","sensitivityPStrat",
"SensoMineR","sensR","separationplot","Sequential","session","sExtinct","sfa",
"sft","SGCS","sgeostat","SGL","SGP","SGPdata","sharpshootR","SHIP",
"siar","sig","sigclust","simboot","SimComp","SimCorMultRes",
"simctest","simecol","simex",
"simexaft","simFrame","Simile","simone","simpleboot","SimpleTable",
"simsem","simSummary","SimultAnR","SIN","sirad",
"SIS","sitools","SixSigma","SiZer","SKAT","SkewHyperbolic","skewt","SLC",
"smacof","smatr","SMC","smco","SMCP","smcure","smcUtils","sme","smfsb","SMIR",
"smirnov","SmithWilsonYieldCurve","SMR","sms","SMVar","someMTP","soobench",
"SortableHTMLTables","sorvi","sos","source.gist","spa","SPA3G","spaa","space",
"spaceExt","spacodiR","spacom","sparcl","sparkTable","SPARQL",
"sparr","sparseHessianFD","sparseLDA","sparseLTSEigen","sparsenet","spartan",
"spatcounts","spate","spatgraphs","spatial.tools","spatialCovariance",
"SpatialEpi","SpatialExtremes","spatialkernel","SpatialNP","SpatialPack",
"spatialprobit","spatialsegregation","SpatialTools","spc","spcadjust","spcov",
"spe","SPECIES","SpeciesMix","spectralGP",
"speedglm","speff2trial","SPEI",
"sperrorest","spgrass6","spgwr","sphereplot","SpherWave","sphet","spi","SPIn",
"splm","spMC","sporm","SPOT","SPSL","spsmooth","spsurvey","spt",
"spTimer","sqldf","sqlutils","SQN","SQUAREM","squash","sra","sROC",
"ssanv","ssize.fdr","sspline","sss","SSsimple","st","stabledist",
"Stack","stacomirtools","stam","stargazer","StatMatch",
"Stem","stepp","stepPlr","stepwise","StMoSim","stocc",
"stochvol","stockPortfolio","stratification","stratigraph","streamR","stremo",
"StressStrength","stringdist","subselect","subtype","SUE","SunterSampling",
"supclust","superdiag","SuperLearner","superpc","SuppDists","support.CEs",
"surface","survAUC","survC1","surveillance","Survgini",
"survivalROC","survPresmooth","survrec",
"survSNP","svapls","svcm","svd","SVMMaj","svmpath",
"SvyNom","SwissAir","symbols","symmoments","synchrony","systemfit",
"table1xls","tableplot","tables","tabplot","tabplotd3","tabuSearch",
"TANOVA","taRifx","taRifx.geo","TauP.R","TBSSurvival","teigen",
"tempdisagg","tensorA","termstrc","TestSurvRec","texmex","TExPosition","TFX",
"tgram","TH.data","thgenetics","ThreeWay","ThresholdROC","Tides","tiff","tiger",
"tightClust","tikzDevice","timeit","timeordered","TimeProjection",
"timereg","timeROC","timetools","TimeWarp","TIMP","timsac","Tinflex",
"tipom","titan","tkrgl","tkrplot","tlemix","tlmec","tlnise",
"tm.plugin.dc","tm.plugin.factiva","tm.plugin.mail",
"tm.plugin.webmining","tmle","tmvtnorm","tnet","tolerance","topicmodels",
"tourr","tourrGui","tpe","TPmsm","track","tractor.base","TraMineR",
"TraMineRextras","TRAMPR","trapezoid","treebase","treecm","treelet",
"treemap","TreePar","TreeSim","treethresh","TRIANGG","triangle",
"trimcluster","tripack","tripEstimation","truncgof","truncreg","truncSP",
"trustOptim","TSA","TScompare","TSdata","tsDyn","tsfa","TSfame",
"TSHRC","tsModel","tsne","TSodbc",
"Tsphere","TSPostgreSQL","TSsdmx","TSSQLite","TSTutorial",
"TTAinterfaceTrendAnalysis","tth","TTR","ttutils","TukeyC","TunePareto",
"turboEM","turner","twang","twiddler",
"TwoCop","twoStageGwasPower","TwoStepCLogit","txtplot","udunits2",
"ump","Unicode","uniCox","upclass","UScensus2000cdp",
"UScensus2000tract","UScensus2010","UsingR","utility","UWHAM",
"varbvs","vardiag","VariABEL","VarianceGamma",
"varSelRF","VarSwapPrice","vcdExtra","VDA","Vdgraph",
"vec2dtransf","VecStatGraphs2D","VecStatGraphs3D","VennDiagram",
"verification","VIF","VIM","violinmplot","vioplot","viopoints",
"visreg","visualFields","VLMC","W2CWM2C","waffect",
"walkscoreAPI","wasim","waterData","waveband","waved",
"wavelets","wavemulcor","waveslim","wccsom","WCQ","WDI","weatherData",
"webvis","WeightedCluster",
"WeightedPortTest","weightedScores","weights","weirs","wfe","wgaim","WhatIf",
"widals","WilcoxCV","wle","WMDB","WriteXLS","x12","x12GUI","XiMpLe","XLConnect",
"xoi","YaleToolkit","yhat","YieldCurve","zendeskR","zic","zipcode");

allpacks=c(getOption('defaultPackages'),basePacks,currentPacks,
  rMetrics,rMetricsRequires,mostCommonDepends ,otherpacks   )

install.Rmetrics(repos="http://cran.us.r-project.org")

install.packages(currentPacks, repos=getOption("repos"));

install.packages(mostCommonDepends,repos=getOption("repos"));

if (others) install.packages(otherpacks,repos=getOption("repos"));

}

